# Generated by Django 3.0.7 on 2020-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
